module.exports = {
	full :
		'/*!\n' +
		" * DON'T EDIT THIS FILE!\n" +
		' * Generated by Gulp in ' + new Date().getFullYear() + '\n' +
		' * Occhio web developers\n' +
		' * http://www.occhio.nl/\n' +
		' * info@occhio.nl\n' +
		' * +31 (0)20 320 78 70\n\n' +
		' * vacatures: https://occhio.homerun.co/' +
		' */\n\n'
};
